### ISSUE TITLE
Phql的update语句仅仅支持数字形式的绑定，不支持字符串形式的绑定问题

### ISSUE THREAD

**Issue by yxgong** [dreamsxin/cphalcon#468]
只有下面这种形式有用：
        $phql = 'UPDATE \M\Forum\ForumThread SET fid = ?0 WHERE tid = ?1 ';
       $this->getModelsManager()->executeQuery($phql, array(13, 891));
     下面这种形式不被支持：
        $phql = 'UPDATE \M\Forum\ForumThread SET fid=:fid: WHERE tid = :tid: ';
        $this->getModelsManager()->executeQuery($phql, array('fid' => 13, 'tid' => '891'));

    如果有1000个回帖，如果一次性地取出来，然后进行逐个进行更新操作，明显不太合适。
而数字形式的绑定，语音层面表达不够清晰，还是字符串的绑定形式明了一些。
请抽时间帮忙增加一下update的字符串绑定这种功能。
​

**Comment by dreamsxin** [comment]
暫時這樣解決
```php
$phql = 'UPDATE \M\Forum\ForumThread SET fid=:fid: WHERE tid = :tid: ';
$this->getModelsManager()->getQuery()->execute($phql, array('fid' => 13, 'tid' => '891'), TRUE);
```
